### PR TITLE
Fix picture transition

### LINKED ISSUE #166: Picture change position when select an user to recommend

### PR DESCRIPTION
**Pull request by EduardoChuks**
- FIX #166 
- Fixing image picker when transition starts from selecting a contact.

### CODE REVIEW

File: app/src/main/java/com/belatrixsf/connect/ui/account/AccountFragment.java [hunk 1]
```diff
@@ -105,6 +105,19 @@ public static AccountFragment newInstance(Integer userId) {
         return accountFragment;
     }
 
+    public static AccountFragment newInstance(Integer userId, byte[] imgBitmap) {
```
Comment (icerrate) [inline app/src/main/java/com/belatrixsf/connect/ui/account/AccountFragment.java:98]: No reason to add a second newInstance() function.
