### PR TITLE
Recommendation hotfix

### LINKED ISSUE #42: SnackBar is shown incorrectly on 6.0
or other versions.

### PR DESCRIPTION
**Pull request by icerrate**
Close #42

### CODE REVIEW

File: app/src/main/java/com/belatrixsf/allstars/ui/givestar/GiveStarFragment.java [hunk 1]
```diff
@@ -98,6 +98,8 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 giveStarPresenter.makeRecommendation();
                 return true;
             default:
+                fragmentListener.setActivityResult(Activity.RESULT_OK);
+                fragmentListener.closeActivity();
                 return super.onOptionsItemSelected(item);
```
Comment (PedroCarrillo) [inline app/src/main/java/com/belatrixsf/allstars/ui/givestar/GiveStarFragment.java:101]: unnecessary

File: app/src/main/res/layout/activity_main.xml [hunk 2]
```diff
@@ -26,9 +26,10 @@
         android:id="@+id/start_recommendation"
         android:layout_width="wrap_content"
         android:layout_height="wrap_content"
-        android:layout_gravity="bottom|right"
+        android:layout_gravity="bottom|end"
         android:layout_margin="@dimen/fab_margin"
         android:tint="@color/white"
-        android:src="@android:drawable/ic_input_add"/>
+        android:src="@android:drawable/ic_input_add"
+        app:layout_behavior="com.belatrixsf.allstars.ui.common.ScrollAwareFABBehavior"/>
```
Comment (PedroCarrillo) [inline app/src/main/res/layout/activity_main.xml:34]: have you tried this behavior with what develop have? Last thing i remember I was having some issues between the tab bars and Floating action button in the coordinator
