### PR TITLE
user and guest sessions fixed

### LINKED ISSUE #181: Login with twitter- having an account
Steps:
- select login with twitter
- fill out you username and password 
- select approve
- fill out your email
- user enter successfully
- Log out
- Select login with twitter

Expected:
- The user is able to complete the flow

Actual:
- After log out , an error message "Can't connect with Twitter Service" appear

Test on:
|HTC One M7 (Android 4.4.3)|
|S4 Active (Android 4.2.2)|
|S4 mini (Android 4.4.2)|

### PR DESCRIPTION
**Pull request by icerrate**
Fix #181 #182 #183

### CODE REVIEW

File: app/src/main/java/com/belatrixsf/connect/ui/home/GuestActivity.java [hunk 1]
```diff
@@ -74,7 +82,39 @@ public boolean onNavigationItemSelected(MenuItem item) {
...
+
+        startActivity(LoginActivity.makeIntent(this));
+        finish();
+    }
+
     public static Intent makeIntent(Context context) {
         return new Intent(context, GuestActivity.class);
     }
+
+    private void ClearCookies(Context context) {
```
Comment (PedroCarrillo) [inline app/src/main/java/com/belatrixsf/connect/ui/home/GuestActivity.java]: capital C?
